image: atlassian/default-image:4

definitions:
  steps:
    - step: &build
        name: build
        script:
          - npm install
          - npm run test
          - npm run build
        artifacts:
            - lib/**

    - step: &release
        name: release
        script:
          - npm run release
          - npm run finalize-package
          - git push --follow-tags origin master

    - step: &publish
        name: publish
        deployment: production
        script:
          - pipe: atlassian/npm-publish:0.3.3
            variables:
              NPM_TOKEN: ${NPM_TOKEN}
              FOLDER: "lib"

pipelines:
  branches:
    master:
      - step: *build
      - step: *release
      - step: *publish
